"""Modified Order & Menu, and add Menu Feature

Revision ID: 4c1495b93c8a
Revises: 6dd25b9df7ce
Create Date: 2023-05-16 17:57:48.350861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1495b93c8a'
down_revision = '6dd25b9df7ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_features',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('spicy', sa.Integer(), nullable=False),
    sa.Column('high_sugar', sa.Integer(), nullable=False),
    sa.Column('high_fat', sa.Integer(), nullable=False),
    sa.Column('high_calorie', sa.Integer(), nullable=False),
    sa.Column('is_light', sa.Integer(), nullable=False),
    sa.Column('is_fried', sa.Integer(), nullable=False),
    sa.Column('contain_water', sa.Integer(), nullable=False),
    sa.Column('has_vegetable', sa.Integer(), nullable=False),
    sa.Column('high_sodium', sa.Integer(), nullable=False),
    sa.Column('high_protein', sa.Integer(), nullable=False),
    sa.Column('high_carbohydrate', sa.Integer(), nullable=False),
    sa.Column('high_cholesterol', sa.Integer(), nullable=False),
    sa.Column('has_chicken', sa.Integer(), nullable=False),
    sa.Column('has_pork', sa.Integer(), nullable=False),
    sa.Column('has_noodle', sa.Integer(), nullable=False),
    sa.Column('high_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menu_features_menu_id'), 'menu_features', ['menu_id'], unique=False)
    op.add_column('menus', sa.Column('breakfast', sa.Float(), nullable=True))
    op.add_column('menus', sa.Column('lunch', sa.Float(), nullable=True))
    op.add_column('menus', sa.Column('dinner', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rating')
    op.drop_column('menus', 'dinner')
    op.drop_column('menus', 'lunch')
    op.drop_column('menus', 'breakfast')
    op.drop_index(op.f('ix_menu_features_menu_id'), table_name='menu_features')
    op.drop_table('menu_features')
    # ### end Alembic commands ###
