"""Add feature relationship to user

Revision ID: af6ae34c3f93
Revises: 2eb9fca090e3
Create Date: 2023-05-14 01:35:06.133265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6ae34c3f93'
down_revision = '2eb9fca090e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
