"""Add more data

Revision ID: d701d7d281f9
Revises: 43ce5b1bec4c
Create Date: 2023-03-19 21:44:44.724385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd701d7d281f9'
down_revision = '43ce5b1bec4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
